name: Build and Deploy to OVH

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy site
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies & Build
        run: |
          npm ci
          npm run build

      - name: Deploy built files to OVH via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.OVH_HOSTING_USER }}
          password: ${{ secrets.OVH_HOSTING_PASSWORD }}
          host: ssh.cluster121.hosting.ovh.net
          local_path: './dist/*'
          remote_path: '/home/upcodew/www'
          sftp_only: true
